
# .github/workflows/build-linux.yml
name: Build Linux Releases
on:
  workflow_dispatch:
jobs:
  build-linux-x64:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install required packages
        run: sudo apt-get install -y rpm
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: get-package-version
        id: package-version
        uses: beaconbrigade/package-json-version@v0.3.2
      - name: Install Dependencies
        run: npm i
      - name: Build script
        run: make linux-x64
      - name: List packages
        uses: mathiasvr/command-output@v2.0.0
        id: packagelist
        with:
          run: node ./build/list-packages.mjs
      - name: Publish Release
        run: gh release upload v${{ steps.package-version.outputs.version}} ${{ steps.packagelist.outputs.stdout }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
