
# .github/workflows/build-windows.yml
name: Build Windows Releases
on:
  workflow_dispatch:
jobs:
  build-win32-x64:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: get-package-version
        id: package-version
        uses: beaconbrigade/package-json-version@v0.3.2
      - name: Install Dependencies
        run: npm i
      - name: Build script
        run: ./build/build.ps1
      - name: List packages
        uses: mathiasvr/command-output@v2.0.0
        id: packagelist
        with:
          run: node ./build/list_packages.mjs
      - name: Publish Release
        run: gh release upload v${{ steps.package-version.outputs.version}} ${{ steps.packagelist.outputs.stdout }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-win32-arm64:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: get-package-version
        id: package-version
        uses: beaconbrigade/package-json-version@v0.3.2
      - name: Install Dependencies
        run: npm i
        env:
          PREBUILDS_ONLY: "1"
          npm_config_arch: "win32"
          npm_config_platform: "arm64"
      - name: Build script
        run: make win-arm64
        env:
          PREBUILDS_ONLY: "1"
          npm_config_arch: "win32"
          npm_config_platform: "arm64"
      - name: List packages
        uses: mathiasvr/command-output@v2.0.0
        id: packagelist
        with:
          run: node ./build/list_packages.mjs
      - name: Publish Release
        run: gh release upload v${{ steps.package-version.outputs.version}} ${{ steps.packagelist.outputs.stdout }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
